 #fisier folosit pentru compilare

all:
	g++ main.cpp OIOprot.h OIOprot.cpp Config.h Config.cpp Aux.h Aux.cpp Timer.h Timer.cpp Tester.h Tester.cpp -pthread -lrt -o ServerOIO

clean:
	rm -f ServerOIO
